# Commands

This chapter will take you through simple and useful commands used by SQLite programmers. These commands are called SQLite dot commands and exception with these commands is that they should not be terminated by a semi-colon (;).

Let's start with typing a simple sqlite3 command at command prompt which will provide you with SQLite command prompt where you will issue various SQLite commands.

```bash
$sqlite3
SQLite version 3.3.6
Enter ".help" for instructions
sqlite>
```

The above command will display a list of various important SQLite dot commands, which are listed in the following table.

<table>
    <tr>
        <td style="width: 100px;"><b>Command</b></td>
        <td><b>Description</b></td>
    </tr>
    <tr>
        <td>.backup ?DB? FILE</td>
        <td>Backup DB (default "main") to FILE</td>
    </tr>
    <tr>
        <td>.bail ON|OFF</td>
        <td>Stop after hitting an error. Default OFF</td>
    </tr>
    <tr>
        <td>.databases</td>
        <td>List names and files of attached databases</td>
    </tr>
    <tr>
        <td>.dump ?TABLE?</td>
        <td>Render database content as SQL</td>
    </tr>
    <tr>
        <td>.echo ON|OFF</td>
        <td>Turn command echo on or off</td>
    </tr>
    <tr>
        <td>.exit</td>
        <td>Exit this program</td>
    </tr>
    <tr>
        <td>.explain ON|OFF</td>
        <td>Turn output mode suitable for EXPLAIN on or off. </td>
    </tr>
    <tr>
        <td>.header(s) ON|OFF</td>
        <td>Turn display of headers on or off</td>
    </tr>
    <tr>
        <td>.help</td>
        <td>Show this message</td>
    </tr>
    <tr>
        <td>.import FILE TABLE</td>
        <td>Import data from FILE into TABLE</td>
    </tr>
    <tr>
        <td>.indices ?TABLE?</td>
        <td>Show names of all indices</td>
    </tr>
    <tr>
        <td>.load FILE ?ENTRY?</td>
        <td>Load an extension library</td>
    </tr>
    <tr>
        <td>.log FILE|off</td>
        <td>Turn logging on or off. FILE can be stderr/stdout</td>
    </tr>
    <tr>
        <td>.mode MODE ?TABLE?</td>
        <td>Set output mode where MODE is one of:<br>
            <ul>
                <li>csv Comma-separated values</li>
                <li>column Left-aligned columns. (See .width)</li>
                <li>html HTML code</li>
                <li>insert SQL insert statements for TABLE</li>
                <li>line One value per line</li>
                <li>list Values delimited by .separator string</li>
                <li>tabs Tab-separated values</li>
                <li>tcl TCL list elements</li>
            </ul>
        </td>
    </tr>
    <tr>
        <td>.nullvalue STRING</td>
        <td>Print STRING in place of NULL values</td>
    </tr>
    <tr>
        <td>.output FILENAME</td>
        <td>Send output to FILENAME</td>
    </tr>
    <tr>
        <td>.output stdout</td>
        <td>Send output to the screen</td>
    </tr>
    <tr>
        <td>.prompt MAIN CONTINUE</td>
        <td>Replace the standard prompts</td>
    </tr>
    <tr>
        <td>.quit</td>
        <td>Exit this program</td>
    </tr>
    <tr>
        <td>.read FILENAME</td>
        <td>Execute SQL in FILENAME</td>
    </tr>
    <tr>
        <td>.restore ?DB? FILE</td>
        <td>Restore content of DB (default "main") from FILE</td>
    </tr>
    <tr>
        <td>.schema ?TABLE?</td>
        <td>Show the CREATE statements</td>
    </tr>
    <tr>
        <td>.separator STRING</td>
        <td>Change separator used by output mode and .import</td>
    </tr>
    <tr>
        <td>.show</td>
        <td>Show the current values for various settings</td>
    </tr>
    <tr>
        <td>.stats ON|OFF</td>
        <td>Turn stats on or off</td>
    </tr>
    <tr>
        <td>.tables ?TABLE?</td>
        <td>List names of tables</td>
    </tr>
    <tr>
        <td>.timeout MS</td>
        <td>Try opening locked tables for MS milliseconds</td>
    </tr>
    <tr>
        <td>.width NUM1 NUM2 ...</td>
        <td>Set column widths for "column" mode</td>
    </tr>
    <tr>
        <td>.timer ON|OFF</td>
        <td>Turn the CPU timer measurement on or off</td>
    </tr>
</table>

The default setting for all these commands is OFF except for .width and .separator which are set to 10 and " " (space) respectively.

```bash
sqlite>.show
     echo: off
  explain: off
  headers: off
     mode: column
nullvalue: ""
   output: stdout
separator: "|"
    width:
sqlite>
```

## Formatting Output

You can use the following sequence of dot commands to format your output.

```bash
sqlite>.header on
sqlite>.mode column
sqlite>.timer on
sqlite>
```

The above setting will produce the output in the following format.

```bash
ID          NAME        AGE         ADDRESS     SALARY
----------  ----------  ----------  ----------  ----------
1           Paul        32          California  20000.0
2           Allen       25          Texas       15000.0
3           Teddy       23          Norway      20000.0
4           Mark        25          Rich-Mond   65000.0
5           David       27          Texas       85000.0
6           Kim         22          South-Hall  45000.0
7           James       24          Houston     10000.0
CPU Time: user 0.000000 sys 0.000000
```

## The sqlite_master Table

The master table holds the key information about your database tables and it is called sqlite_master. You can see its schema as follows.

```bash
sqlite>.schema sqlite_master
CREATE TABLE sqlite_master (
  type text,
  name text,
  tbl_name text,
  rootpage integer,
  sql text
);
```