# Vector Operation


## name()
Suppose we have a vector that contains the production years of four movies. It may be difficult to remember which movies these years belong to, so we can use the `name` function to map a title to each year.

```R
years <- c(1994, 1972, 1974, 2008)
names(years) <- c("The Shawshank Redemption", "The Godfather", "The Godfather: Part II", "The Dark Knight")
years

#[1] 1994 1972 1974 2008
```

## sort()
The `sort` function sorts a vector in ascending order. If we want to sort the vector in descending order, we can use the `rev` function to reverse the order of the elements.

```R
sort(years)
rev(sort(years))

#[1] 1972 1974 1994 2008
#[2] 2008 1994 1974 1972
```

## length()
The `length` function returns the number of elements in a vector.

```R
length(years)

#[1] 4
```

## sum()
The `sum` function returns the sum of the elements in a vector.

```R
sum(years)

#[1] 7958
```

## mean()
The `mean` function returns the mean of the elements in a vector.

```R
mean(years)

#[1] 1989.5
```

## median()
The `median` function returns the median of the elements in a vector.

```R
median(years)

#[1] 1984
```

## max()
The `max` function returns the maximum value of the elements in a vector.

```R
max(years)

#[1] 2008
```

## min()
The `min` function returns the minimum value of the elements in a vector.

```R
min(years)

#[1] 1972
```

## range()
The `range` function returns the minimum and maximum values of the elements in a vector.

```R
range(years)

#[1] 1972 2008
```

## summary()
The `summary` function returns the minimum, first quartile, median, mean, third quartile, and maximum of the elements in a vector.

```R
summary(years)

#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
#  1972    1973    1984    1989    2000    2008
```

## unique()
The `unique` function returns a vector with all duplicate elements removed.

```R
years <- c(1994, 1972, 1974, 2008, 1994, 1994)
unique(years)

#[1] 1994 1972 1974 2008
```

## rep()
The `rep` function replicates a vector a specified number of times.

```R
rep(years, 2)

#[1] 1994 1972 1974 2008 1994 1994 1994 1972 1974 2008 1994 1994
```

## paste()
The `paste` function concatenates the elements of a vector into a single string.

```R
paste(years, collapse = ", ")

#[1] "1994, 1972, 1974, 2008"
```

## paste0()
The `paste0` function concatenates the elements of a vector into a single string without any separator.

```R
paste0(years, collapse = ", ")

#[1] "1994, 1972, 1974, 2008"
```

## strsplit()
The `strsplit` function splits a string into a vector of substrings.

```R
strsplit("1994, 1972, 1974, 2008", ", ")

#[[1]]
#[1] "1994" "1972" "1974" "2008"
```

## substr()
The `substr` function extracts a substring from a string.

```R
substr("1994, 1972, 1974, 2008", 1, 4)

#[1] "1994"
```

## toupper()
The `toupper` function converts a string to uppercase.

```R
toupper("The Shawshank Redemption")

#[1] "THE SHAWSHANK REDEMPTION"
```

## tolower()
The `tolower` function converts a string to lowercase.

```R
tolower("The Shawshank Redemption")

#[1] "the shawshank redemption"
```

## grep()
The `grep` function searches for a pattern in a string and returns the index of the first match.

```R
grep("Shawshank", c("The Shawshank Redemption", "The Godfather", "The Godfather: Part II", "The Dark Knight"))

#[1] 1
```

## grepl()
The `grepl` function searches for a pattern in a string and returns a logical vector indicating whether a match was found.

```R
grepl("Shawshank", c("The Shawshank Redemption", "The Godfather", "The Godfather: Part II", "The Dark Knight"))

#[1]  TRUE FALSE FALSE FALSE
```

## sub()
The `sub` function replaces the first match of a pattern in a string with a replacement string.

```R
sub("Shawshank", "The Shawshank Redemption", "The Shawshank Redemption")

#[1] "The Shawshank Redemption"
```

## gsub()
The `gsub` function replaces all matches of a pattern in a string with a replacement string.

```R
gsub("Shawshank", "The Shawshank Redemption", "The Shawshank Redemption")

#[1] "The Shawshank Redemption"
```

# Vector index

In order to retrieve an element of a vector, you simply need to write the vectors name, followed by the desired index in square brackets.

```R
years <- c(1994, 1972, 1974, 2008)
years[1]

#[1] 1994
```

You can also retrieve multiple elements of a vector by specifying a vector of indices.

```R
years[c(1, 3)]

#[1] 1994 1974
```

Retrieve a range of value also the same way.

```R
years[1:3]

#[1] 1994 1972 1974
```

Negative value working quite different than Python, it will return all elements except the specified indices.

```R
years[-1]

#[1] 1972 1974 2008
```

If we pull a out of range index, it will return `NA`.

```R
years[5]

#[1] NA
```

We can pull a conditional index too, it have some equivalent to logical operator.

```R
years[years > 1994]

#[1] 2008

years > 1994

#[1] FALSE FALSE FALSE  TRUE
```

# Missing Value

Missing values are represented in R by the symbol `NA` (not available). If we try to perform a calculation on a vector that contains a missing value, the result will also be `NA`. Not like Python, it will raise an error.

```R
years <- c(1994, 1972, 1974, 2008, NA)
sum(years)

#[1] NA
```

# Vector arithmetic

We can perform arithmetic operations on vectors. When we do this, the operation is performed element-wise.

```R
years <- c(1994, 1972, 1974, 2008)
years + 10

#[1] 2004 1982 1984 2018
```

We can also perform arithmetic operations on two vectors. When we do this, the operation is performed element-wise.

```R
years <- c(1994, 1972, 1974, 2008)
years2 <- c(1994, 1972, 1974, 2008)
years + years2

#[1] 3988 3944 3948 4016
```

In this chapter, I already summarize all the vector operation that I know. If you want to know more, you can check the [R documentation](https://www.rdocumentation.org/).